### ISSUE TITLE
Wind Differentials

### ISSUE THREAD

**Issue by Blast-Cat** [geosheehan/web-artillery-strike#1]
Please my lord.

Add a wind differential feature. In the left diagram we can grab A to C by doing the regular calculation, then solve for A to D by flipping the A to C azimuth and inputting C to D with the wind data. 

Wind data is the azimuth of the flag direction and its distance. The player would be supplying D to C in this instance, so it would need to be flipped as well.

![image](https://user-images.githubusercontent.com/8700376/118430101-4a736b00-b6a1-11eb-8d47-13f76a1be49d.png)

**Comment by geosheehan** [comment]
I think you mean flipping C to D azimuth, where C to D is the wind vector

**Comment by geosheehan** [comment]
Feature added.
